package io.muserver;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;

import java.nio.ByteBuffer;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import static io.muserver.FieldBlockEncoderTest.hexToByteArray;
import static org.junit.jupiter.api.Assertions.*;

/** Published response sequences from RFC 7541 Appendices C.5 and C.6. */
class HpackResponseExamplesTest {
    private static final String DATE_21 = "Mon, 21 Oct 2013 20:13:21 GMT";
    private static final String DATE_22 = "Mon, 21 Oct 2013 20:13:22 GMT";
    private static final String LOCATION = "https://www.example.com";
    private static final String COOKIE = "foo=ASDJKHQKBZXOQWEOPIUAXQWEOIU; max-age=3600; version=1";

    // Independent wire fixtures, not output generated by the encoder under test.
    private static final String[] PLAIN = {
        "4803333032580770726976617465611d4d6f6e2c203231204f63742032303133"
            + "2032303a31333a323120474d546e1768747470733a2f2f7777772e6578616d706c652e636f6d",
        "4803333037c1c0bf",
        "88c1611d4d6f6e2c203231204f637420323031332032303a31333a323220474d54c05a04677a6970"
            + "7738666f6f3d4153444a4b48514b425a584f5157454f50495541585157454f49553b206d61782d616765"
            + "3d333630303b2076657273696f6e3d31"
    };
    private static final String[] HUFFMAN = {
        "488264025885aec3771a4b6196d07abe941054d444a8200595040b8166e082a62d1bff"
            + "6e919d29ad171863c78f0b97c8e9ae82ae43d3",
        "4883640effc1c0bf",
        "88c16196d07abe941054d444a8200595040b8166e084a62d1bffc05a839bd9ab77ad"
            + "94e7821dd7f2e6c7b335dfdfcd5b3960d5af27087f3672c1ab270fb5291f9587316065c003ed4ee5b1063d5007"
    };

    @ParameterizedTest(name = "Huffman={0}, buffer={1}")
    @CsvSource({"false,heap", "true,heap", "false,direct", "true,direct", "false,readonly", "true,readonly"})
    void consecutiveResponsesPreserveFieldsAndEvictThePublishedEntries(boolean huffman, String bufferKind) throws Exception {
        HpackTable table = new HpackTable(256);
        FieldBlockDecoder decoder = new FieldBlockDecoder(table, 8192, 8192);
        String[] blocks = huffman ? HUFFMAN : PLAIN;

        assertFields(decode(decoder, blocks[0], bufferKind),
            field(":status", "302"), field("cache-control", "private"), field("date", DATE_21), field("location", LOCATION));
        assertTable(table, 222,
            field("location", LOCATION), field("date", DATE_21), field("cache-control", "private"), field(":status", "302"));

        assertFields(decode(decoder, blocks[1], bufferKind),
            field(":status", "307"), field("cache-control", "private"), field("date", DATE_21), field("location", LOCATION));
        assertTable(table, 222,
            field(":status", "307"), field("location", LOCATION), field("date", DATE_21), field("cache-control", "private"));

        assertFields(decode(decoder, blocks[2], bufferKind),
            field(":status", "200"), field("cache-control", "private"), field("date", DATE_22), field("location", LOCATION),
            field("content-encoding", "gzip"), field("set-cookie", COOKIE));
        assertTable(table, 215, field("set-cookie", COOKIE), field("content-encoding", "gzip"), field("date", DATE_22));
    }

    private static FieldBlock decode(FieldBlockDecoder decoder, String hex, String kind) throws Exception {
        byte[] wire = hexToByteArray(hex);
        ByteBuffer input = kind.equals("direct") ? ByteBuffer.allocateDirect(wire.length + 2) : ByteBuffer.allocate(wire.length + 2);
        input.put((byte) 42).put(wire).put((byte) 43).flip();
        input.position(1).limit(1 + wire.length);
        if (kind.equals("readonly")) input = input.asReadOnlyBuffer();
        FieldBlock result = decoder.decodeFrom(input);
        assertEquals(input.limit(), input.position(), "Entire response block must be consumed");
        input.limit(input.capacity());
        assertEquals(43, input.get(), "Bytes after this block must remain untouched");
        return result;
    }

    private static Map.Entry<String, String> field(String name, String value) {
        return Map.entry(name, value);
    }

    @SafeVarargs
    private static void assertFields(FieldBlock actual, Map.Entry<String, String>... expected) {
        assertEquals(List.of(expected), actual.entries().stream()
            .map(entry -> Map.entry(entry.getKey(), entry.getValue())).collect(Collectors.toList()));
    }

    @SafeVarargs
    private static void assertTable(HpackTable table, int bytes, Map.Entry<String, String>... expected) throws Exception {
        assertEquals(256, table.maxSize());
        assertEquals(bytes, table.dynamicTableSizeInBytes(), "Size uses decoded octets, including with Huffman coding");
        for (int i = 0; i < expected.length; i++) {
            FieldLine line = table.getValue(62 + i);
            assertEquals(expected[i].getKey(), line.getKey(), "Name at dynamic index " + (i + 1));
            assertEquals(expected[i].getValue(), line.getValue(), "Value at dynamic index " + (i + 1));
        }
        Http2Exception error = assertThrows(Http2Exception.class, () -> table.getValue(62 + expected.length));
        assertEquals(Http2ErrorCode.COMPRESSION_ERROR, error.errorCode(), "No stale entry may survive eviction");
    }
}
