package io.muserver;

import io.netty.buffer.ByteBuf;
import io.netty.buffer.Unpooled;
import io.netty.channel.ChannelHandlerContext;
import io.netty.channel.ChannelInboundHandlerAdapter;
import io.netty.channel.embedded.EmbeddedChannel;
import org.junit.Test;

import java.util.ArrayList;
import java.util.List;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.*;

/**
 * This test is generated by claude
 */
public class PreReaderTest {

    private final List<Object> forwarded = new ArrayList<>();
    private final ChannelInboundHandlerAdapter recordingHandler = new ChannelInboundHandlerAdapter() {
        @Override
        public void channelRead(ChannelHandlerContext ctx, Object msg) {
            forwarded.add(msg);
        }
    };

    @Test
    public void inboundMessagesAreBufferedUntilReadIsRequested() {
        EmbeddedChannel channel = new EmbeddedChannel(new PreReader(), recordingHandler);

        ByteBuf msg = Unpooled.wrappedBuffer(new byte[]{1, 2, 3});
        channel.writeOneInbound(msg);

        assertThat(forwarded, is(empty()));

        channel.read();

        // With the new code path, sendItMaybe runs synchronously inside read() because
        // EmbeddedEventLoop.inEventLoop() returns true. Without runPendingTasks(),
        // the buffered message must already have been forwarded.
        assertThat(forwarded, hasSize(1));
        assertThat(forwarded.get(0), is(sameInstance(msg)));

        channel.finishAndReleaseAll();
    }

    @Test
    public void readBeforeMessageArrivesCausesNextMessageToBeForwarded() {
        EmbeddedChannel channel = new EmbeddedChannel(new PreReader(), recordingHandler);

        channel.read();
        assertThat(forwarded, is(empty()));

        ByteBuf msg = Unpooled.wrappedBuffer(new byte[]{4, 5, 6});
        channel.writeOneInbound(msg);

        assertThat(forwarded, hasSize(1));
        assertThat(forwarded.get(0), is(sameInstance(msg)));

        channel.finishAndReleaseAll();
    }

    @Test
    public void onlyOneMessageIsForwardedPerRead() {
        EmbeddedChannel channel = new EmbeddedChannel(new PreReader(), recordingHandler);

        ByteBuf msg1 = Unpooled.wrappedBuffer(new byte[]{1});
        ByteBuf msg2 = Unpooled.wrappedBuffer(new byte[]{2});
        channel.writeOneInbound(msg1);
        // Second message overwrites the pending one (only one message is buffered at a time)
        channel.writeOneInbound(msg2);

        channel.read();

        assertThat(forwarded, hasSize(1));
        assertThat(forwarded.get(0), is(sameInstance(msg2)));

        channel.finishAndReleaseAll();
    }

    @Test
    public void pendingMessageIsReleasedOnChannelUnregister() {
        EmbeddedChannel channel = new EmbeddedChannel(new PreReader());

        ByteBuf msg = Unpooled.wrappedBuffer(new byte[]{1, 2, 3});
        int initialRefCnt = msg.refCnt();
        channel.writeOneInbound(msg);
        // PreReader retained the message, so refCnt is bumped
        assertThat(msg.refCnt(), is(initialRefCnt + 1));

        channel.close();
        channel.finishAndReleaseAll();

        // After unregister + drain, the retained reference must have been released
        assertThat(msg.refCnt(), is(0));
    }
}
